# Site settings
title: Kevin Herrera
email: kevin@herrera.io
description: The personal website of Kevin Herrera, a software engineer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Identity
your-name: Kevin Herrera
your-title: Software Engineer

# Social settings
avatar_url: https://www.gravatar.com/avatar/4c259c8faf621a04a489aa2f2497fc43?s=122
500px_url:
facebook_url:
github_url: https://github.com/kherge
gitlab_url: https://gitlab.com/kherge
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/kherge
pinterest_url:
slack_url:
twitter_url: https://twitter.com/kherge

# Build settings
markdown: kramdown
